import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as K from '../dist/economy.js';
import * as E from '../dist/engine.js';
import * as B from '../dist/studio-growth.js';
import * as C from '../dist/cinema.js';
import * as T from '../dist/taxes.js';
const base=E.createGame('시장 검증',20260912),fresh=()=>structuredClone(base);
const eq=(a,b)=>assert.ok(Math.abs(a-b)<.00001,`${a} !== ${b}`);
function draft(s,extra={}){const script=s.pitches.find(p=>E.available(s,E.person(s,p.writer))&&!E.busyFilm(s,p.writer));return E.recommend(s,{script,title:script.title,genres:[script.genre],scale:'small',runtime:120,leads:[],supports:[],...extra});}
function done(extra={}){const s=fresh(),f=E.greenlight(s,draft(s,extra));Object.assign(f,{status:'ready',readyMonth:s.month,elapsedWeeks:f.months*4,elapsed:f.months,completionAcknowledged:true,productionCompletedWeek:s.week});C.makeCriticReviews(f);C.ensurePlot(f);return{s,f};}
function project({cost=100,investment=25}={}){const s={week:0,month:0,economyVersion:1,difficulty:'normal'},f={company:'c0',spent:cost,script:{},receipts:0};K.initFilmEconomy(s,f);if(investment)f.investment={amount:investment,share:.6*investment/cost,paid:0,principalRecovered:0,profitPaid:0};return{s,f};}

test('exactly five ordered difficulties; absent setting defaults to normal',()=>{assert.equal(K.DIFFICULTIES.length,5);assert.equal(K.difficulty({}).id,'normal');assert.equal(base.difficulty,'normal');eq(E.player(base).cash,150);});
for(const x of K.DIFFICULTIES)test(`${x.name}: founding cash, ledger, feature parity, save persistence`,()=>{const s=E.createGame('난이도',19,0,x.id);eq(E.player(s).cash,x.capital);eq(s.ledger.find(l=>l.kind==='capital').amount,x.capital);assert.equal(s.companies.length,10);assert.equal(s.roster.length,1600);assert.equal(s.pitches.length,6);assert.equal(E.migrateSave(structuredClone(s)).difficulty,x.id);eq(T.monthlyCosts(s).base,E.round(.25*x.overhead));});
test('invalid difficulty cannot found or load a game',()=>{assert.throws(()=>E.createGame('실패',1,0,'impossible'));assert.equal(E.validateSave({...base,difficulty:'wrong'}),false);});
test('same seed has identical scripts, people and AI across difficulty',()=>{const a=E.createGame('A',71,0,'very-easy'),b=E.createGame('A',71,0,'very-hard');assert.deepEqual(a.roster,b.roster);assert.deepEqual(a.pitches,b.pitches);assert.deepEqual(a.films,b.films);});
test('legacy save defaults normal, preserves cash, dates, movies and transactions',()=>{const s=fresh();delete s.difficulty;delete s.economyVersion;for(const f of s.films){delete f.economy;f.distribution??=null;}s.companies[0].cash=31.47;const before=JSON.stringify([s.companies,s.films,s.ledger,s.week]);E.migrateSave(s);assert.equal(s.difficulty,'normal');assert.equal(JSON.stringify([s.companies,s.films,s.ledger,s.week]),before);});
test('fixed fee differs by role and grows smoothly with fame, not episode count',()=>{const p={skill:70,star:20,fee:2};for(const role of ['writer','director','lead','support']){assert.ok(K.marketFee(base,{...p,role,star:85})>K.marketFee(base,{...p,role}));}assert.ok(K.marketFee(base,{...p,role:'lead',star:85})>K.marketFee(base,{...p,role:'support',star:85}));eq(K.marketFee({},p),2);});
test('all generated people yield finite positive contract quotes',()=>{for(const p of base.roster){const q=E.contractQuote(base,p);assert.ok(q.fee>0&&Number.isFinite(q.fee));}});
test('theatre waterfall conserves gross and separates VAT/exhibitor/distributor/royalty',()=>{const {f}=project();f.script.license={share:.08};const x=K.theatricalSettlement(f,100000,1);eq(x.gross,9.8);eq(x.gross,x.vat+x.exhibitor+x.distribution+x.royalty+x.pool);assert.ok(x.pool<9.8*.5);});
test('legacy ticket and settlement still use old 10000-won and half-share rule',()=>{const f={script:{license:{share:.1}}},q=K.theatricalSettlement(f,100000);eq(q.gross,10);eq(q.royalty,.5);eq(q.pool,4.5);});
test('zero receipts do not create principal or profits; negative rejected',()=>{const {s,f}=project();eq(K.splitProjectReceipt(s,f,0),0);eq(f.investment.paid,0);assert.throws(()=>K.splitProjectReceipt(s,f,-1));});
test('before recoupment: recover 25% actual external cost, no investment profit',()=>{const {s,f}=project();eq(K.splitProjectReceipt(s,f,40),30);eq(f.investment.principalRecovered,10);eq(f.investment.profitPaid,0);eq(f.economy.returnedCost,40);});
test('crossing break-even splits only remaining profit at 15%, not entire revenue',()=>{const {s,f}=project();K.splitProjectReceipt(s,f,40);eq(K.splitProjectReceipt(s,f,80),62);eq(f.investment.principalRecovered,25);eq(f.investment.profitPaid,3);eq(f.economy.profitPool,20);});
test('investment principal cannot be recovered twice from OTT then foreign payouts',()=>{const {s,f}=project();K.splitProjectReceipt(s,f,100);eq(K.splitProjectReceipt(s,f,100),85);eq(f.investment.principalRecovered,25);eq(f.investment.profitPaid,15);eq(f.investment.paid,40);});
test('new production expenses after break-even are recovered by the self-funding producer',()=>{const {s,f}=project();K.splitProjectReceipt(s,f,120);f.spent+=20;eq(K.splitProjectReceipt(s,f,20),20);eq(f.investment.principalRecovered,25);eq(f.investment.profitPaid,3);eq(f.economy.returnedCost,120);});
test('additional costs before recoupment do not over-recover external principal',()=>{const {s,f}=project();K.splitProjectReceipt(s,f,40);f.spent+=20;K.splitProjectReceipt(s,f,80);eq(f.investment.principalRecovered,25);eq(f.economy.returnedCost,120);eq(f.economy.profitPool,0);});
test('one-cent rounding conserves money across hundreds of settlements',()=>{const {s,f}=project({cost:1,investment:.33});let total=0,net=0;for(let j=0;j<500;j++){total=E.round(total+.01);net=E.round(net+K.splitProjectReceipt(s,f,.01));}eq(net+f.investment.paid,total);eq(f.investment.principalRecovered,.33);assert.equal(f.economy.settlements.length,256);});
test('self-financed films retain all eligible receipts',()=>{const {s,f}=project({investment:0});eq(K.splitProjectReceipt(s,f,120),120);eq(f.economy.profitPool,20);});
test('old signed investment keeps old share despite upgraded game',()=>{const f={investment:{share:.30,paid:0},spent:100};eq(B.splitReceipt(base,f,40),28);eq(f.investment.paid,12);assert.equal(f.economy,undefined);});
test('new investor offers distinguish funding from profit rights',()=>{const s=fresh(),d=draft(s),q=B.investorOffers(s,d,E.estimate(d,s));assert.deepEqual(q.map(x=>x.funding),[.25,.4,.55]);assert.deepEqual(q.map(x=>x.share),[.15,.24,.33]);});
test('greenlight pays fees once, snapshots terms, deducts own-funded expense for tax',()=>{const s=fresh(),d=draft(s,{investorId:'seed'}),q=E.estimate(d,s),before=E.player(s).cash,f=E.greenlight(s,d);eq(E.player(s).cash,E.round(before-q.cashNeeded));assert.equal(f.investment.model,'cost-recovery-v1');eq(s.ledger.find(l=>l.kind==='production').externalFunding,f.investment.amount);eq(T.taxPosition(s).expenses,q.cashNeeded);assert.throws(()=>E.greenlight(s,d));});
test('appearance contracts are not repriced after ability changes or migration',()=>{const {s,f}=done(),contracts=JSON.stringify(f.contracts),budget=f.budget;E.person(s,f.leads[0]).star=100;E.migrateSave(s);assert.equal(JSON.stringify(f.contracts),contracts);eq(f.budget,budget);});
test('OTT payout equals cost-recovery preview and persists entire settlement',()=>{const {s,f}=done({investorId:'seed'}),offer=C.ottOffers(f)[0],copy=structuredClone(f),expected=K.splitProjectReceipt(s,copy,offer.net),cash=E.player(s).cash;E.sellToOTT(s,f.id,offer.platform);eq(E.player(s).cash,E.round(cash+expected));eq(f.receipts,expected);eq(f.investment.principalRecovered,copy.investment.principalRecovered);assert.deepEqual(E.migrateSave(structuredClone(s)).films.find(x=>x.id===f.id).economy,f.economy);});
test('foreign fixed deal uses same cumulative recovery as prior channels',()=>{const {s,f}=done({investorId:'seed'});K.splitProjectReceipt(s,f,f.spent);const before=f.investment.principalRecovered;B.signForeign(s,f.id,'east','fixed');eq(f.investment.principalRecovered,before);assert.ok(f.foreignDeals.length===1);});
test('new difficult film changes demand/offer only, not scores or quality',()=>{const {s,f}=done(),easy=structuredClone(f),hard=structuredClone(f);K.initFilmEconomy({...s,difficulty:'very-easy'},easy);K.initFilmEconomy({...s,difficulty:'very-hard'},hard);eq(easy.quality,hard.quality);assert.deepEqual(easy.reviews,hard.reviews);assert.ok(K.demandFactor(easy)>K.demandFactor(hard));assert.ok(C.ottOffers(easy)[0].amount>C.ottOffers(hard)[0].amount);});
test('weekly domestic settlement stores auditable breakdown without touching old cash',()=>{const {s,f}=done({investorId:'seed'});E.releaseFilm(s,f.id);E.advanceWeek(s);const r=f.runs[0];assert.ok(r);eq(r.gross,r.settlement.gross);eq(f.economy.theatrical.pool,r.settlement.pool);eq(r.receipts+f.investment.paid,r.settlement.pool);});
test('break-even estimate uses unrecovered cost and decreases with other channel recovery',()=>{const {s,f}=project();const first=K.breakEvenAudience(f);K.splitProjectReceipt(s,f,50);assert.ok(K.breakEvenAudience(f)<first);K.splitProjectReceipt(s,f,50);eq(K.breakEvenAudience(f),0);});
test('native difficulty selection updates in place, does not rerender the picker',()=>{const app=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');assert.match(app,/id="difficulty" name="difficulty"/);assert.match(app,/get\('difficulty'\)\?\?'normal'/);assert.match(app,/difficulty-capital.*textContent/);});

for(const [label,edit] of [
 ['negative cumulative receipts',f=>f.economy.projectReceipts=-1],
 ['unknown snapshot version',f=>f.economy.version=99],
 ['missing settlement data',f=>delete f.economy.theatrical],
 ['over-recovered principal',f=>f.investment.principalRecovered=f.investment.amount+1]
])test(`malformed imported economy rejected: ${label}`,()=>{const{s,f}=done({investorId:'seed'});assert.ok(E.validateSave(s));edit(f);assert.equal(E.validateSave(s),false);});
test('displayed person fees use the actual new quote, not the legacy growth reference',()=>{const app=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');const card=app.slice(app.indexOf('function personCard('),app.indexOf('function pagination('));assert.match(card,/E\.contractQuote\(game,p\)/);assert.doesNotMatch(card,/E\.money\(p\.fee\)/);});
