import test from 'node:test';
import assert from 'node:assert/strict';
import {createNavigation,screenKey} from '../dist/navigation.js';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const screen=(view='studio',modal=null)=>({home:false,view,modal,state:{market:'boxoffice',people:{role:'director',query:''},step:0},scroll:{page:0}});
function harness(initial=screen(),blocked=false){
 let active=structuredClone(initial),position=0;const visits=[null],handlers=new Set();
 const win={history:{get state(){return visits[position]},get length(){return visits.length},
  replaceState(s){if(blocked)throw Error('SecurityError');visits[position]=structuredClone(s)},
  pushState(s){if(blocked)throw Error('SecurityError');visits.splice(++position);visits.push(structuredClone(s))},
  go(delta){if(position+delta<0||position+delta>=visits.length)return;position+=delta;queueMicrotask(()=>handlers.forEach(fn=>fn({state:visits[position]})))}},
  addEventListener(_,fn){handlers.add(fn)},removeEventListener(_,fn){handlers.delete(fn)}};
 const options={window:win,read:()=>active,restore:s=>active=s,home:()=>({...screen(),home:true})};
 const nav=createNavigation(options);nav.start();
 return {nav,win,options,get current(){return active},set(s){active=structuredClone(s);nav.schedule()}};
}
test('navigation initializes a home boundary before the saved studio',()=>{const h=harness();assert.equal(h.win.history.length,2);assert.equal(h.win.history.state.index,1);assert.equal(h.current.home,false)});
test('browser back and forward restore screens, not simulation data',async()=>{const h=harness();const game={week:20,cash:42};h.set(screen('scripts'));await tick();h.set(screen('talents'));await tick();game.week++;game.cash-=5;h.win.history.go(-1);await tick();assert.equal(h.current.view,'scripts');h.win.history.go(1);await tick();assert.equal(h.current.view,'talents');assert.deepEqual(game,{week:21,cash:37})});
test('search and filter updates replace one entry rather than filling history',async()=>{const h=harness(screen('talents'));const n=h.win.history.length;for(const query of ['김','김태','김태윤']){h.set({...screen('talents'),state:{people:{role:'director',query}}});await tick();}assert.equal(h.win.history.length,n);assert.equal(h.win.history.state.screen.state.people.query,'김태윤')});
test('more -> guide -> back -> more -> close returns to the underlying screen',async()=>{const h=harness(screen('talents'));h.set(screen('talents',{type:'more'}));await tick();h.set(screen('talents',{type:'help'}));await tick();h.nav.back();await tick();assert.equal(h.current.modal.type,'more');h.nav.back();await tick();assert.equal(h.current.modal,null);assert.equal(h.current.view,'talents')});
test('closing an action modal collapses the duplicate desk entry',async()=>{const h=harness();h.set(screen('studio',{type:'refresh-confirm'}));await tick();const index=h.win.history.state.index;h.set(screen());await tick();await tick();assert.equal(h.win.history.state.index,index-1);assert.equal(h.current.modal,null)});
test('back restores the scroll and filter snapshot captured before a modal',async()=>{const h=harness(screen('talents'));h.current.scroll.page=128;h.current.state.people.query='박';h.nav.remember();h.set(screen('talents',{type:'person',id:'p1'}));await tick();h.nav.back();await tick();assert.equal(h.current.scroll.page,128);assert.equal(h.current.state.people.query,'박')});
test('rapid duplicate close requests do not skip the more screen',async()=>{const h=harness();h.set(screen('studio',{type:'more'}));await tick();h.set(screen('studio',{type:'versions'}));await tick();h.nav.back();h.nav.back();await tick();assert.equal(h.current.modal.type,'more')});
test('reload can restore the saved history entry',async()=>{const h=harness();h.set(screen('market',{type:'versions'}));await tick();h.nav.dispose();h.current.view='studio';h.current.modal=null;const next=createNavigation(h.options);next.start();assert.equal(h.current.view,'market');assert.equal(h.current.modal.type,'versions');next.dispose()});
test('sandboxed previews retain in-app close behavior when pushState is prohibited',async()=>{const h=harness(screen(),true);h.set(screen('scripts'));await tick();h.set(screen('scripts',{type:'more'}));await tick();assert.equal(h.nav.back(),true);assert.equal(h.current.modal,null);assert.equal(h.current.view,'scripts')});
test('the real root is not an endless back-button trap',async()=>{const h=harness();h.nav.back();await tick();assert.equal(h.current.home,true);assert.equal(h.nav.back(),false);assert.equal(h.win.history.state.index,0)});
test('multiple renders in one click create only the final modal entry',async()=>{const h=harness();h.set(screen('market',{type:'film-chart',id:'f1'}));h.set(screen('market',{type:'film-chart',id:'f1',metric:'gross'}));await tick();assert.equal(h.win.history.length,3);assert.equal(h.win.history.state.screen.modal.metric,'gross')});
test('market tabs and wizard steps are distinct screens',()=>{assert.notEqual(screenKey(screen('market')),screenKey({...screen('market'),state:{market:'schedule'}}));assert.notEqual(screenKey(screen('scripts',{type:'wizard'})),screenKey({...screen('scripts',{type:'wizard'}),state:{step:1}}))});
test('a new company invalidates historical screens instead of reviving the old game',async()=>{const h=harness();h.set(screen('scripts'));await tick();h.nav.reset();h.win.history.go(-1);await tick();assert.equal(h.current.home,true);assert.equal(h.current.modal,null)});
test('Close skips internal film tabs and returns to the parent person',async()=>{const h=harness(screen('talents'));h.set(screen('talents',{type:'person',id:'p1'}));await tick();h.set({...screen('talents',{type:'film',id:'f1'}),state:{filmTab:'overview'}});await tick();h.set({...screen('talents',{type:'film',id:'f1'}),state:{filmTab:'timeline'}});await tick();h.nav.closeModal();await tick();assert.deepEqual(h.current.modal,{type:'person',id:'p1'})});
test('internal wizard back consumes the existing entry instead of pushing a reverse step',async()=>{const h=harness(screen('scripts'));h.set({...screen('scripts',{type:'wizard'}),state:{step:0}});await tick();h.set({...screen('scripts',{type:'wizard'}),state:{step:1}});await tick();h.set({...screen('scripts',{type:'wizard'}),state:{step:0}});await tick();await tick();assert.equal(h.win.history.state.index,2);assert.equal(h.current.state.step,0)});
