"""Offline browser checks of the shipped modules; no implementation mocks."""
import json,sys,subprocess,traceback,argparse
from pathlib import Path
import browser_support as m
from playwright.sync_api import sync_playwright
p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=m.ROOT/'qa-output');args=p.parse_args();OUT=args.output.resolve();OUT.mkdir(parents=True,exist_ok=True)
subprocess.run(['node',str(m.ROOT/'tests/studio-v12-fixtures.js'),str(OUT)],check=True)
subprocess.run(['node',str(m.ROOT/'tests/make-browser-fixtures.js'),str(OUT)],check=True)
payload=m.fixture_payload();checks=[];errors=[];meta=json.loads((OUT/'v12-meta.json').read_text());fid=meta['filmId']
def state(page):return page.evaluate("JSON.parse(localStorage.getItem('last-take-game-v1'))")
def action(page,a,extra=''):
 selector=f'[data-action="{a}"]'+extra
 modal=page.locator('dialog[open] '+selector)
 return modal.first if modal.count() else page.locator(selector).first
def check(name,condition=True):assert condition,name;checks.append(name);print('PASS',name,flush=True)
def shot(page,name):page.screenshot(path=str(OUT/(name+'.png')))
def newpage(b,fixture=None,w=1366,h=768):
 page=b.new_page(viewport={'width':w,'height':h});page.set_default_timeout(4500);page.on('pageerror',lambda e:errors.append(str(e)));saved=json.loads((OUT/fixture).read_text()) if fixture else None;m.load(page,payload,saved);return page
def nav(page,name):
 selector=f'[data-action="nav"][data-view="{name}"]'
 for button in page.locator(selector).all():
  if button.is_visible():
   button.click();return
 action(page,'more').click()
 page.locator('dialog[open] '+selector).first.click()
def settled(page):page.wait_for_selector('#week-transition[hidden]',state='attached');page.wait_for_timeout(100)
def overflow(page):return page.evaluate('document.documentElement.scrollWidth<=innerWidth+1')
def dismiss_popups(page):
 # Use the actual close button, as a player would before tapping content below it.
 for _ in range(12):
  close=page.locator('#notification-popups [data-action="dismiss-notification"]')
  if not close.count():return
  close.first.click()
 raise AssertionError('notification queue did not close')
try:
 with sync_playwright() as p:
  b=m.launch_browser(p)
  page=newpage(b,'v12-market.json');nav(page,'market');rows=page.locator('.v12-box-row');check('box office shows cumulative audience and two rating types',rows.count()>0 and rows.first.locator('.boxoffice-cumulative').is_visible() and rows.first.locator('.rating-button').count()==2);shot(page,'boxoffice-desktop')
  own=page.locator(f'.v12-box-row:has([data-action="film"][data-id="{fid}"])').first
  own.locator('[data-action="critic-reviews"]').click();check('critic score opens four detailed viewpoints',page.locator('.review-card').count()==4);shot(page,'critic-reviews-desktop');action(page,'review-page','[data-delta="1"]').click();check('critic review pagination exposes remaining three',page.locator('.review-card').count()==3);action(page,'feature-back').click()
  own.locator('[data-action="audience-reviews"]').click();check('audience score opens independent viewer reviews',page.locator('.review-card').count()==6 and '관객 종합평' in page.locator('dialog').inner_text());action(page,'feature-back').click()
  own.locator('[data-action="film-chart"][data-key="gross"]').click();check('weekly gross trend opens a real SVG record graph',page.locator('.history-chart').count()==1 and page.locator('.chart-dot').count()==3);page.locator('#history-point').fill('0');page.locator('#history-point').dispatch_event('input');check('graph inspection slider selects first stored point',page.locator('#history-point').input_value()=='0');shot(page,'weekly-gross-graph-desktop');page.keyboard.press('Escape');check('Escape returns from graph to box office',not page.locator('dialog').is_visible())
  own.locator('[data-action="film"]').first.click();check('film header has clickable studio and performers',page.locator('.film-top-credits .person-chip').count()==4);shot(page,'film-detail-desktop');action(page,'company-info').click();check('header studio opens company works',page.locator('.company-works').count()==1);action(page,'feature-back').click();action(page,'person-peek').click();check('header performer opens actual profile',page.locator('dialog').get_attribute('data-modal')=='person');page.keyboard.press('Escape');check('profile Escape restores film detail',page.locator('dialog').get_attribute('data-modal')=='film');check('completed film shows plot with expandable resolution',page.locator('.plot-details').count()==1 and '줄거리' in page.locator('dialog').inner_text());action(page,'film-tab','[data-id="history"]').click();check('production event history is retained','현장 결정 기록 · 4건' in page.locator('dialog').inner_text());action(page,'close').click()
  nav(page,'finance');check('recent finance list contains exactly ten transactions',page.locator('.recent-ledger .ledger-entry').count()==10);action(page,'ledger').click();check('transaction details show more records and filters',page.locator('.ledger-entry').count()>10);action(page,'feature-back').click()
  for key in ['cash','receipts','debt','fixed','net','ott']:
   action(page,'finance-chart',f'[data-id="{key}"]').click();check('historical finance graph '+key,page.locator('.history-chart').count()==1);action(page,'feature-back').click()
  action(page,'finance-chart','[data-id="cash"]').click();shot(page,'finance-graph-desktop');page.keyboard.press('Escape');page.close()
  page=newpage(b,'v12-ready.json');action(page,'film',f'[data-id="{fid}"]').click();action(page,'ott-offers').click();check('OTT quote popup has five distinct selectable services',page.locator('.ott-offer').count()==5 and action(page,'ott-confirm').is_disabled());cash=state(page)['companies'][0]['cash'];action(page,'select-ott','[data-id="nemoflix"]').click();action(page,'select-ott','[data-id="dizring"]').click();check('one OTT selection without cash movement',page.locator('.ott-offer.selected').count()==1 and state(page)['companies'][0]['cash']==cash);shot(page,'ott-offers-desktop');action(page,'ott-confirm').click();check('OTT requires separate confirmation',page.locator('dialog').get_attribute('data-modal')=='ott-confirm' and state(page)['companies'][0]['cash']==cash);action(page,'ott-sign').click();check('OTT commit adds cash once and navigates to catalog',page.locator('.ott-film-card').count()==1 and state(page)['companies'][0]['cash']>cash);check('viewer score is unavailable until one week passes',page.locator('.ott-film-card [data-action="audience-reviews"]').is_disabled());action(page,'advance').click();settled(page);check('OTT viewer reviews unlock after a week',page.locator('.ott-film-card [data-action="audience-reviews"]').is_enabled());shot(page,'ott-catalog-desktop');page.close()
  page=newpage(b,'fixture-fresh.json');nav(page,'scripts');action(page,'pitch').click();field=page.locator('#film-title');field.fill('별 사이');field.focus();page.keyboard.press('Space');check('Space is typed normally in film-title input',field.input_value()=='별 사이 ');page.locator('dialog #dialog-title').click();page.keyboard.press('Space');check('Space activates wizard next step',page.locator('.cast-slots').count()>0 or action(page,'recommend').is_visible());action(page,'recommend').click();action(page,'wizard-back').click();check('all four presentation options are available',page.locator('[data-field="format-toggle"]').count()==4);page.locator('[data-field="format-toggle"][value="imax"]').check();check('selected presentation format stays checked',page.locator('[data-field="format-toggle"][value="imax"]').is_checked());action(page,'wizard-next').click();check('chemistry panel includes clickable portraits',page.locator('.team-person-grid .person-chip').count()==8);page.locator('.team-chemistry>summary').click();person=page.locator('.team-person-grid [data-action="person-peek"]').first;person.click();check('team profile opens without destroying draft',page.locator('dialog').get_attribute('data-modal')=='person');action(page,'close').click();check('closing team profile restores wizard',page.locator('dialog').get_attribute('data-modal')=='wizard' and page.locator('.team-person-grid .person-chip').count()==8);shot(page,'casting-desktop');action(page,'close').click()
  nav(page,'talents');check('renamed menu is shown','인물정보' in page.locator('body').inner_text());page.locator('#people-sort').select_option('skill-asc');vals=page.locator('.person-stats>span:first-child b').all_text_contents();check('ascending person sort orders skill',list(map(int,vals))==sorted(map(int,vals)));page.locator('#people-sort').select_option('skill-desc');vals=page.locator('.person-stats>span:first-child b').all_text_contents();check('descending person sort orders skill',list(map(int,vals))==sorted(map(int,vals),reverse=True));shot(page,'people-desktop')
  check('non-editable right-click is prevented',page.evaluate("(()=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true});document.querySelector('.person-card').dispatchEvent(e);return e.defaultPrevented})()"));check('text input right-click remains available',page.evaluate("(()=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true});document.querySelector('#people-query').dispatchEvent(e);return !e.defaultPrevented})()"));check('game cards disable text selection',page.locator('.person-card').first.evaluate("e=>getComputedStyle(e).userSelect==='none'"));nav(page,'studio');before=state(page)['week'];page.locator('h1').click();page.keyboard.down('Space');page.keyboard.down('Space');settled(page);page.keyboard.up('Space');check('holding Space advances one week only',state(page)['week']==before+1);page.close()
  for w,h in [(390,844),(320,568),(844,390),(768,1024),(1366,768)]:
   page=newpage(b,'v12-market.json',w,h);nav(page,'market');check(f'boxoffice {w}x{h} no horizontal overflow',overflow(page));check(f'boxoffice {w}x{h} cumulative and weekly values visible',page.locator('.boxoffice-cumulative').first.is_visible() and page.locator('.weekly-metrics').first.is_visible());shot(page,f'boxoffice-{w}x{h}');action(page,'critic-reviews').click();check(f'review modal {w}x{h} fits width',page.locator('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1'));shot(page,f'reviews-{w}x{h}');action(page,'feature-back').click();nav(page,'finance');check(f'finance {w}x{h} no horizontal overflow',overflow(page));action(page,'finance-chart','[data-id="cash"]').click();check(f'finance graph {w}x{h} fits',page.locator('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1'));shot(page,f'finance-graph-{w}x{h}');page.keyboard.press('Escape');nav(page,'talents');check(f'people grid {w}x{h} no horizontal overflow',overflow(page));shot(page,f'people-{w}x{h}');page.close()
  for w,h in [(320,568),(390,844),(844,390)]:
   page=newpage(b,'v12-ready.json',w,h);action(page,'film',f'[data-id="{fid}"]').click();check(f'film detail {w}x{h} fits width',page.locator('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1'));shot(page,f'film-detail-{w}x{h}')
   action(page,'ott-offers').click();check(f'OTT offers {w}x{h} show five services without horizontal overflow',page.locator('.ott-offer').count()==5 and page.locator('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1'));action(page,'select-ott','[data-id="wavelet"]').click();shot(page,f'ott-offers-{w}x{h}');action(page,'ott-confirm').click();check(f'OTT confirmation {w}x{h} keeps contract button on screen',action(page,'ott-sign').evaluate('e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1}'));action(page,'ott-sign').click();check(f'OTT catalog {w}x{h} has no horizontal overflow',overflow(page) and page.locator('.ott-film-card').count()==1);action(page,'advance').click();settled(page);check(f'OTT viewer rating {w}x{h} becomes clickable after one week',page.locator('.ott-film-card [data-action="audience-reviews"]').is_enabled());dismiss_popups(page);shot(page,f'ott-catalog-{w}x{h}');page.locator('.ott-film-card [data-action="audience-reviews"]').click();check(f'OTT viewer detail {w}x{h} fits width',page.locator('dialog').evaluate('e=>e.scrollWidth<=e.clientWidth+1'));page.close()
  for w,h in [(390,844),(320,568),(844,390),(1366,768)]:
   page=newpage(b,None,w,h);check(f'start screen {w}x{h} has no vertical scroll',page.evaluate('document.documentElement.scrollHeight<=innerHeight+1'));page.close()
  check('zero browser JavaScript errors',not errors);b.close()
except Exception as e:
 print('BROWSER FAILURE',str(e),flush=True);traceback.print_exc();(OUT/'studio-v12-browser-report.json').write_text(json.dumps({'checks':checks,'errors':errors,'failure':str(e)},ensure_ascii=False,indent=2));raise
(OUT/'studio-v12-browser-report.json').write_text(json.dumps({'checks':checks,'errors':errors,'failure':None},ensure_ascii=False,indent=2));print('ALL',len(checks),'PASSED')
