import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../dist/engine.js';
import * as B from '../dist/studio-growth.js';
import * as C from '../dist/cinema.js';
import * as T from '../dist/taxes.js';
import * as V from '../dist/save-vault.js';
import * as N from '../dist/casting.js';
import {EVENTS} from '../dist/data.js';
import {cloneNavigationState} from '../dist/navigation.js';
const base=E.createGame('확장 기능 검증',20260912),copy=structuredClone,snap=JSON.stringify;
const fresh=()=>copy(base);
function draft(s,extra={}){const script=s.pitches.find(p=>E.available(s,E.person(s,p.writer))&&!E.busyFilm(s,p.writer));return E.recommend(s,{script,title:script.title,genres:[script.genre],scale:'small',runtime:120,leads:[],supports:[],...extra});}
// v1.6: independent expected first-payment waterfall, replacing flat revenue-share assertions.
function firstNet(f,pool,additionalCost=0){const cost=E.round(f.spent+additionalCost),recovery=Math.min(pool,cost),principal=E.round(recovery*f.investment.amount/cost),profit=E.round(Math.max(0,pool-recovery)*f.investment.share);return E.round(pool-principal-profit);}

function done(extra={}){const s=fresh(),d=draft(s,extra),f=E.greenlight(s,d);Object.assign(f,{status:'ready',readyMonth:s.month,elapsedWeeks:f.months*4,elapsed:f.months,completionAcknowledged:true,productionCompletedWeek:s.week});C.makeCriticReviews(f);C.ensurePlot(f);return{s,f,d};}
function tick(s,n=1){for(let i=0;i<n;i++){s.week++;s.month=Math.floor(s.week/4);B.tickGrowth(s);}}
function step(s){for(const f of E.pendingEvents(s))E.resolveEvent(s,f.id,EVENTS[f.pending][2].findIndex(o=>o[1]===0));E.advanceWeek(s);}
function rejectsUnchanged(s,fn,re){const before=snap(s);assert.throws(fn,re);assert.equal(snap(s),before);}

test('v15 migration adds optional records without rewriting existing money or film results',()=>{const s=fresh();delete s.studioGrowth;const money=snap(s.companies.map(c=>[c.cash,c.debt,c.totalGross])),films=snap(s.films);B.initGrowth(s);assert.equal(snap(s.companies.map(c=>[c.cash,c.debt,c.totalGross])),money);assert.equal(snap(s.films),films);const after=snap(s);B.initGrowth(s);assert.equal(snap(s),after);assert.ok(E.validateSave(s));});
test('favorites toggle stable person IDs, persist and reject unknown IDs',()=>{const s=fresh(),id=s.roster[0].id;assert.equal(B.toggleFavorite(s,id),true);assert.deepEqual(copy(s).studioGrowth.favorites,[id]);assert.equal(B.toggleFavorite(s,id),false);assert.equal(s.studioGrowth.favorites.length,0);rejectsUnchanged(s,()=>B.toggleFavorite(s,'missing'));});
test('saved production teams retain seven roles, clear approvals and never spend money',()=>{const s=fresh(),d=draft(s),cash=E.player(s).cash,t=B.saveTeam(s,d,'단골 팀');d.castingAgreements={old:'x'};const x=B.loadTeam(s,d,t.id);assert.deepEqual(x.draft.leads,t.leads);assert.equal(x.draft.director,t.director);assert.equal(x.draft.supports.length,4);assert.equal(x.missing.length,0);assert.deepEqual(x.draft.castingAgreements,{});assert.equal(E.player(s).cash,cash);});
test('retired and occupied cast become vacancies when loading a saved team',()=>{const s=fresh(),d=draft(s),t=B.saveTeam(s,d,'팀'),f=E.greenlight(s,d),next=draft(s);const x=B.loadTeam(s,next,t.id);assert.equal(x.missing.length,7);assert.equal(x.draft.director,null);f.status='closed';E.person(s,t.director).status='retired';assert.equal(B.loadTeam(s,next,t.id).draft.director,null);});
test('team limit and incomplete draft checks are enforced before adding records',()=>{const s=fresh(),d=draft(s);rejectsUnchanged(s,()=>B.saveTeam(s,{...d,director:null},'팀'));for(let i=0;i<12;i++)B.saveTeam(s,d,'팀 '+i);rejectsUnchanged(s,()=>B.saveTeam(s,d,'초과'));B.removeSaved(s,'teams',s.studioGrowth.teams[0].id);assert.equal(s.studioGrowth.teams.length,11);});
test('draft archive copies input, preserves expired proposals, resets approvals and removes contracted drafts',()=>{const s=fresh(),d=draft(s),item=B.archiveDraft(s,d,2);d.title='원본 변경';assert.notEqual(item.draft.title,d.title);s.pitches=[];const x=B.restoreDraft(s,item.id);assert.equal(s.pitches[0].id,x.draft.script.id);assert.equal(x.step,0);assert.deepEqual(x.draft.castingAgreements,{});x.draft.requireNegotiation=false;E.greenlight(s,x.draft);assert.equal(s.studioGrowth.drafts.length,0);});
test('one auto draft replaces itself while eight direct drafts remain separate',()=>{const s=fresh(),d=draft(s);for(let i=0;i<8;i++)B.archiveDraft(s,d,0);B.archiveDraft(s,d,1,{automatic:true});B.archiveDraft(s,{...d,title:'변경'},2,{automatic:true});assert.equal(s.studioGrowth.drafts.length,9);assert.equal(s.studioGrowth.drafts.find(x=>x.id==='auto-draft').title,'변경');const count=s.studioGrowth.drafts.length;assert.throws(()=>B.archiveDraft(s,d));assert.equal(s.studioGrowth.drafts.length,count);});
test('facility quotes do not debit and lease/own upkeep is separately calculated',()=>{const s=fresh(),cash=E.player(s).cash;B.facilityQuote(s,'editing','lease');assert.equal(E.player(s).cash,cash);B.changeFacility(s,'editing','lease');assert.equal(E.player(s).cash,E.round(cash-.4));assert.equal(B.facilityMonthlyCost(s),.12);assert.equal(T.monthlyCosts(s).base,.37);rejectsUnchanged(s,()=>B.changeFacility(s,'editing','lease'));B.changeFacility(s,'editing','own');assert.equal(B.facilityMonthlyCost(s),.03);B.changeFacility(s,'editing','remove');assert.equal(B.facilityMonthlyCost(s),0);assert.equal(E.player(s).cash,E.round(cash-.4-6+2.4));});
test('facility effects apply to future technical costs and frozen contract snapshots only',()=>{const s=fresh(),d=draft(s),before=E.estimate(d,s);for(const x of B.FACILITIES)B.changeFacility(s,x.id,'lease');const after=E.estimate(d,s);assert.equal(after.writer,before.writer);assert.equal(after.cast,before.cast);assert.ok(after.total<before.total);assert.equal(after.months,before.months-1);assert.equal(after.facilitySnapshot.names.length,3);const f=E.greenlight(s,d),snapshot=snap(f.facilitySnapshot),budget=f.budget;B.changeFacility(s,'stage','remove');assert.equal(snap(f.facilitySnapshot),snapshot);assert.equal(f.budget,budget);const ai=E.estimate({...draft(s),company:'c1'},s);assert.equal(ai.facilitySavings,0);});
test('facility expense is collected once per four live weeks, not every week',()=>{const s=fresh();B.changeFacility(s,'editing','lease');const money=E.player(s).cash;step(s);assert.equal(E.player(s).cash,money);step(s);step(s);step(s);assert.equal(E.player(s).cash,E.round(money-.25-.12));});
test('investor offers are deterministic previews with distinct shares and no funds transferred',()=>{const s=fresh(),d=draft(s),e=E.estimate(d,s),before=snap(s),offers=B.investorOffers(s,d,e);assert.equal(offers.length,3);assert.equal(new Set(offers.map(x=>x.amount)).size,3);assert.deepEqual(offers,B.investorOffers(s,d,e));assert.equal(snap(s),before);});
test('joint production receives contribution and spends full budget once without creating debt',()=>{const s=fresh(),d=draft(s,{investorId:'seed'}),e=E.estimate(d,s),cash=E.player(s).cash,debt=E.player(s).debt,f=E.greenlight(s,d);assert.equal(f.investment.amount,e.finance.amount);assert.equal(E.player(s).cash,E.round(cash-e.cashNeeded));assert.equal(E.player(s).debt,debt);assert.equal(s.ledger.filter(l=>l.filmId===f.id&&l.kind==='investment').length,1);assert.equal(s.ledger.filter(l=>l.filmId===f.id&&l.kind==='production').length,1);rejectsUnchanged(s,()=>E.greenlight(s,d));assert.equal(B.filmProfit(f),-e.cashNeeded);});
test('unfulfilled investor runtime or invalid provider rejects before any debit',()=>{const s=fresh(),d=draft(s,{investorId:'tempo',runtime:180});rejectsUnchanged(s,()=>E.greenlight(s,d),/투자/);d.investorId='unknown';rejectsUnchanged(s,()=>E.greenlight(s,d));});
test('investment contribution is not a sale in the tax model',()=>{const s=fresh(),d=draft(s,{investorId:'seed'});E.greenlight(s,d);const before=T.monthlyCosts(s);const noContribution=copy(s);noContribution.ledger=noContribution.ledger.filter(l=>l.kind!=='investment');assert.equal(T.monthlyCosts(noContribution).tax,before.tax);});
test('OTT sharing returns precisely the producer net and never counts theatrical receipts',()=>{const {s,f}=done({investorId:'seed'}),offer=C.ottOffers(f)[0],net=firstNet(f,offer.net),cash=E.player(s).cash;E.sellToOTT(s,f.id,offer.platform);assert.equal(E.player(s).cash,E.round(cash+net));assert.equal(f.receipts,net);assert.equal(f.ott.producerNet,net);assert.equal(f.investment.paid,E.round(offer.net-net));assert.equal(f.audience,0);rejectsUnchanged(s,()=>E.sellToOTT(s,f.id,offer.platform));});
test('domestic weekly receipts pay the investor after source royalty exactly once',()=>{const {s,f}=done({investorId:'seed'});E.releaseFilm(s,f.id);step(s);const r=f.runs[0],expected=firstNet(f,r.settlement.pool);assert.equal(r.receipts,expected);assert.ok(f.investment.paid>0);});
test('late investor adjustment is only five percentage points once and has no immediate cash fine',()=>{const {s,f}=done({investorId:'seed'}),cash=E.player(s).cash;s.week=f.investment.deadline;tick(s);assert.equal(f.investment.share,.20);assert.equal(E.player(s).cash,cash);tick(s,6);assert.equal(f.investment.share,.20);assert.equal(s.notifications.filter(n=>n.key?.endsWith('investment-late')).length,1);});
test('a test screening charges once and live week progression delivers three audience viewpoints',()=>{const {s,f}=done(),cash=E.player(s).cash;B.startScreening(s,f.id);assert.equal(E.player(s).cash,E.round(cash-B.screeningFee(f)));assert.equal(f.screening.status,'running');rejectsUnchanged(s,()=>B.startScreening(s,f.id));rejectsUnchanged(s,()=>E.releaseFilm(s,f.id),/시사회/);step(s);assert.equal(f.screening.status,'decision');assert.equal(f.screening.groups.length,3);assert.equal(B.screeningOptions(s,f).length,3);});
test('keeping the original is free and unlocks distribution',()=>{const {s,f}=done();B.startScreening(s,f.id);tick(s);const cash=E.player(s).cash,quality=f.quality;B.decideScreening(s,f.id,'keep');assert.equal(E.player(s).cash,cash);assert.equal(f.quality,quality);assert.equal(f.screening.status,'done');assert.doesNotThrow(()=>E.releaseFilm(s,f.id));rejectsUnchanged(s,()=>B.decideScreening(s,f.id,'keep'));});
test('recut respects its paid delay and applies bounded quality only at completion',()=>{const {s,f}=done();B.startScreening(s,f.id);tick(s);const q=f.quality,cost=B.screeningOptions(s,f).find(x=>x.id==='recut').cost,cash=E.player(s).cash;B.decideScreening(s,f.id,'recut');assert.equal(f.quality,q);assert.equal(E.player(s).cash,E.round(cash-cost));rejectsUnchanged(s,()=>E.sellToOTT(s,f.id,'nemoflix'));tick(s);assert.equal(f.screening.status,'done');assert.ok(f.quality<=q+3);const finished=snap(f);B.tickGrowth(s);assert.equal(snap(f),finished);});
test('supplemental screening shoot reserves people and saved teams skip them',()=>{const {s,f,d}=done(),t=B.saveTeam(s,d,'촬영팀');B.startScreening(s,f.id);tick(s);B.decideScreening(s,f.id,'reshoot');assert.equal(E.busyFilm(s,f.director).id,f.id);const next=draft(s);assert.equal(B.loadTeam(s,next,t.id).draft.director,null);next.director=f.director;rejectsUnchanged(s,()=>E.greenlight(s,next),/제작 중/);tick(s,2);assert.equal(E.busyFilm(s,f.director),undefined);});
test('crew conflict disables supplemental shoot without any side effects',()=>{const {s,f}=done();const d=draft(s);d.director=f.director;E.greenlight(s,d);B.startScreening(s,f.id);tick(s);assert.equal(B.screeningOptions(s,f).find(x=>x.id==='reshoot').unavailable,true);rejectsUnchanged(s,()=>B.decideScreening(s,f.id,'reshoot'),/일정/);});
test('foreign offers vary by region and genre without rerolling or accounting mutation',()=>{const {s,f}=done(),before=snap(s),q=B.foreignOffers(s,f);assert.equal(q.length,5);assert.equal(new Set(q.map(x=>x.upfront)).size,5);assert.deepEqual(q,B.foreignOffers(s,f));assert.notDeepEqual(q.map(x=>x.upfront),B.foreignOffers(s,{...f,genres:['sf']}).map(x=>x.upfront));assert.equal(snap(s),before);});
test('foreign buyout posts localization and royalties plus investor share without domestic inflation',()=>{const {s,f}=done({investorId:'seed'});f.script.license={share:.1};const q=B.foreignOffers(s,f)[0],cash=E.player(s).cash,beforeShare=E.round(q.upfront-E.round(q.upfront*.1)),expected=firstNet(f,beforeShare,q.localization);const deal=B.signForeign(s,f.id,q.id,'fixed');assert.equal(deal.receipts,expected);assert.equal(E.player(s).cash,E.round(cash-q.localization+expected));assert.equal(E.player(s).totalForeignReceipts,expected);assert.equal(f.gross,0);assert.equal(f.audience,0);assert.equal(f.runs.length,0);rejectsUnchanged(s,()=>B.signForeign(s,f.id,q.id,'fixed'));rejectsUnchanged(s,()=>E.sellToOTT(s,f.id,'nemoflix'),/해외/);});
test('foreign participation pays eight actual weekly installments and then stops',()=>{const {s,f}=done(),q=B.foreignOffers(s,f)[0],d=B.signForeign(s,f.id,q.id,'share');assert.equal(d.receipts,0);for(let i=0;i<8;i++){tick(s);assert.equal(d.runs.length,i+1);const before=snap(s);B.tickGrowth(s);assert.equal(snap(s),before);}assert.equal(d.status,'complete');const cash=E.player(s).cash;tick(s,4);assert.equal(E.player(s).cash,cash);assert.equal(d.runs.length,8);assert.equal(E.round(d.runs.reduce((n,r)=>n+r.receipts,0)),d.receipts);});
test('foreign sale rejects OTT, unfinished movie, lack of localization funds and unknown mode',()=>{const {s,f}=done();rejectsUnchanged(s,()=>B.signForeign(s,f.id,'east','wrong'));E.player(s).cash=0;rejectsUnchanged(s,()=>B.signForeign(s,f.id,'east','fixed'),/자금/);E.player(s).cash=10;E.sellToOTT(s,f.id,'nemoflix');rejectsUnchanged(s,()=>B.signForeign(s,f.id,'east','fixed'));});
test('franchise variants produce persistent, free pitches tied to their parent',()=>{const {s,f}=done();E.releaseFilm(s,f.id);const cash=E.player(s).cash;for(const [type]of B.SERIES_TYPES){const p=B.createSeriesPitch(s,f.id,type);assert.equal(p.seriesPlan.parent,f.id);assert.equal(p.seriesPlan.root,f.id);assert.ok(p.synopsis.length>70);assert.equal(p.seriesPlan.type,type);}assert.equal(E.player(s).cash,cash);rejectsUnchanged(s,()=>B.createSeriesPitch(s,f.id,'sequel'),/이미/);});
test('franchise fan base, fatigue and production continuity affect capped initial demand',()=>{const {s,f}=done();E.releaseFilm(s,f.id);f.audience=3000000;const p=B.createSeriesPitch(s,f.id,'sequel'),d=draft(s,{script:p,genres:f.genres,director:f.director});d.director=f.director;d.leads=f.leads;let a=B.seriesForecast(s,d);assert.ok(a.fans>0);const b=B.seriesForecast(s,{...d,director:'unknown',leads:[]});assert.ok(a.factor>b.factor);for(let i=0;i<5;i++)s.films.push({...copy(f),id:'recent'+i,seriesRoot:f.id});const fatigued=B.seriesForecast(s,d);assert.ok(fatigued.factor<a.factor);assert.ok(fatigued.factor>=.8&&fatigued.factor<=1.2);});
test('franchise identity and expectation effect are frozen when production starts',()=>{const {s,f}=done();E.releaseFilm(s,f.id);const p=B.createSeriesPitch(s,f.id,'prequel'),d=draft(s,{script:p});const expected=B.seriesForecast(s,d).factor,child=E.greenlight(s,d);assert.equal(child.seriesRoot,f.id);assert.equal(child.seriesPlan.type,'prequel');assert.equal(child.seriesBoost,expected);const stored=child.seriesBoost;f.audience+=1000000;assert.equal(child.seriesBoost,stored);});
test('festival windows, premiere eligibility and repeat-entry restrictions are explicit',()=>{const {s,f}=done();let q=B.festivalOpportunities(s,f).find(x=>x.id==='spring');assert.equal(q.eligible,false);s.week=q.openWeek;s.month=Math.floor(s.week/4);q=B.festivalOpportunities(s,f).find(x=>x.id==='spring');assert.equal(q.eligible,true);const cash=E.player(s).cash;B.submitFestival(s,f.id,'spring');assert.equal(E.player(s).cash,E.round(cash-q.fee));rejectsUnchanged(s,()=>B.submitFestival(s,f.id,'spring'));rejectsUnchanged(s,()=>E.releaseFilm(s,f.id),/영화제/);rejectsUnchanged(s,()=>E.sellToOTT(s,f.id,'nemoflix'));rejectsUnchanged(s,()=>B.signForeign(s,f.id,'east','fixed'));});
test('withdrawing festival entry gives no refund but releases its premiere restriction',()=>{const {s,f}=done();s.week=4;s.month=1;const x=B.submitFestival(s,f.id,'spring'),cash=E.player(s).cash;B.withdrawFestival(s,f.id,x.key);assert.equal(E.player(s).cash,cash);assert.equal(x.status,'withdrawn');assert.doesNotThrow(()=>E.releaseFilm(s,f.id));rejectsUnchanged(s,()=>B.withdrawFestival(s,f.id,x.key));});
test('festival due week publishes a single selection result and clears restriction',()=>{const {s,f}=done();s.week=4;s.month=1;const x=B.submitFestival(s,f.id,'spring');s.week=x.dueWeek-1;tick(s);assert.ok(['selected','winner','not-selected'].includes(x.status));assert.doesNotThrow(()=>B.assertDistribution(s,f));const trophies=E.player(s).trophies,awards=f.awards.length,notices=s.notifications.filter(n=>n.key?.endsWith(x.key+':result')).length;assert.equal(notices,1);tick(s,3);assert.equal(f.awards.length,awards);assert.equal(E.player(s).trophies,trophies);});
test('festival prestige improves foreign offer without rewriting earlier deals',()=>{const {s,f}=done(),q=B.foreignOffers(s,f)[0];B.signForeign(s,f.id,'east','fixed');const old=f.foreignDeals[0].upfront;f.festivalEntries=[{status:'winner'}];assert.ok(B.foreignOffers(s,f)[0].upfront>q.upfront);assert.equal(f.foreignDeals[0].upfront,old);});
test('save JSON roundtrip retains drafts, favorites, facilities and contracts',()=>{const {s,f,d}=done({investorId:'seed'});B.toggleFavorite(s,f.director);B.changeFacility(s,'sound','lease');const pending=draft(s);B.archiveDraft(s,pending);B.saveTeam(s,d,'기록 팀');B.signForeign(s,f.id,'east','share');const envelope=V.exportSave(s),loaded=V.parseSave(JSON.stringify(envelope));assert.equal(loaded.companies[0].cash,s.companies[0].cash);assert.deepEqual(loaded.studioGrowth,s.studioGrowth);assert.deepEqual(loaded.films.find(x=>x.id===f.id).foreignDeals,f.foreignDeals);assert.ok(E.validateSave(loaded));});
test('save import rejects corrupt checksums, future formats, unsafe keys and malformed records',()=>{const s=fresh(),p=V.exportSave(s);p.game.companies[0].cash++;assert.throws(()=>V.parseSave(JSON.stringify(p)),/무결성/);p.formatVersion=99;assert.throws(()=>V.parseSave(JSON.stringify(p)));assert.throws(()=>V.parseSave('{"__proto__":{}}'));assert.throws(()=>V.parseSave('not json'));s.studioGrowth.facilities.editing={mode:'invalid'};assert.throws(()=>V.parseSave(JSON.stringify(s)),/시설/);});
test('original raw saves migrate and new UI snapshots remain clone safe',()=>{const s=fresh();delete s.studioGrowth;const x=V.parseSave(JSON.stringify(s));assert.equal(x.studioGrowth.version,1);const d=draft(x),frame=cloneNavigationState({view:'studio',modal:{type:'growth-confirm',id:'1'},draft:d,peekStack:[{modal:{type:'growth-foreign',id:'f1'}}]});assert.doesNotThrow(()=>structuredClone(frame));assert.equal(typeof frame.modal.id,'string');});
test('save vault fails clearly without IndexedDB and never pretends to save',async()=>{const original=globalThis.indexedDB;try{delete globalThis.indexedDB;await assert.rejects(()=>V.putSave('manual-1',fresh()),/저장 슬롯/);await assert.rejects(()=>V.putSave('invalid',fresh()),/슬롯/);}finally{if(original)globalThis.indexedDB=original;}});

// Storage lifecycle verified through a labeled API double, not native browser disk.
import {installMemoryIndexedDB} from './vault-memory-double.js';
test('vault API double: completed writes, exact restore, overwrite isolation and deletion',async()=>{
 const idb=installMemoryIndexedDB(),s=fresh();await V.putSave('manual-1',s);assert.equal(idb.events.at(-1),'complete');const old=s.companies[0].cash;s.companies[0].cash-=1;await V.putSave('manual-2',s);assert.equal((await V.getSave('manual-1')).companies[0].cash,old);assert.equal((await V.getSave('manual-2')).companies[0].cash,old-1);assert.equal((await V.listSaves()).length,2);idb.failNextWrite=true;await assert.rejects(()=>V.putSave('manual-1',s),/저장하지 못했습니다/);assert.equal((await V.getSave('manual-1')).companies[0].cash,old);await V.deleteSave('manual-2');assert.equal((await V.listSaves()).length,1);await assert.rejects(()=>V.getSave('manual-2'),/비어/);
});
